name: Build and Deploy Docker Image

on: [push]

jobs:
  build-and-deploy:
    name: "Build and Deploy Docker images"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: |
        docker build -t docker.pkg.github.com/bbzblit/m426-ui/app:latest .
    - name: Login to GitHub Packages
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin
    - name: Push Docker Image
      run: |
        docker push docker.pkg.github.com/bbzblit/m426-ui/app:latest
